site_name: Awesome Utrecht University
site_description: A curated list of awesome projects from Utrecht University. The purpose of this repository is to have a selection of projects that scored high on openness criteria and stars in order to showcase good examples of open practices.
site_author: Keven Quach
repo_name: UtrechtUniversity/awesome-utrecht-university
repo_url: https://github.com/UtrechtUniversity/awesome-utrecht-university
edit_uri: ""
theme:
  name: mkdocs